export const SEARCH_CONFIG = {
  MAX_CANDIDATES: 10,
  CACHE_TTL: 900, // 15 minutes in seconds
  MAX_HISTORY: 15,
  MINIMUM_RELEVANCE_THRESHOLD: 70, // Reject weak matching results
  RELEVANCE_WEIGHTS: {
    category: 0.45,
    keyword: 0.25,
    brand: 0.15,
    budget: 0.10,
    rating: 0.05
  },
  // Catalog awareness categories mappings
  SUPPORTED_CATEGORIES: [
    'smartphone', 
    'laptop', 
    'television', 
    'earbuds', 
    'book', 
    'clothing', 
    'keyboard', 
    'mouse', 
    'shoes',
    'headphone',
    'charger',
    'mount',
    'accessories',
    'home appliances',
    'gaming gear'
  ],
  CATEGORY_ALIASES: {
    'phone': 'smartphone',
    'phones': 'smartphone',
    'mobile': 'smartphone',
    'mobiles': 'smartphone',
    'smartphone': 'smartphone',
    'smartphones': 'smartphone',
    'laptop': 'laptop',
    'laptops': 'laptop',
    'tv': 'television',
    'tvs': 'television',
    'television': 'television',
    'televisions': 'television',
    'book': 'book',
    'books': 'book',
    'clothing': 'clothing',
    'clothes': 'clothing',
    'tshirt': 'clothing',
    'tshirts': 'clothing',
    'shirt': 'clothing',
    'shirts': 'clothing',
    'pant': 'clothing',
    'pants': 'clothing',
    'shoe': 'shoes',
    'shoes': 'shoes',
    'sneaker': 'shoes',
    'sneakers': 'shoes',
    'headphone': 'headphone',
    'headphones': 'headphone',
    'earbud': 'earbuds',
    'earbuds': 'earbuds',
    'keyboard': 'keyboard',
    'keyboards': 'keyboard',
    'mouse': 'mouse',
    'mice': 'mouse',
    'accessory': 'accessories',
    'accessories': 'accessories',
    'charger': 'accessories',
    'chargers': 'accessories',
    'cable': 'accessories',
    'cables': 'accessories',
    'mount': 'accessories',
    'mounts': 'accessories',
    'stand': 'accessories',
    'stands': 'accessories',
    'appliance': 'home appliances',
    'appliances': 'home appliances',
    'home appliance': 'home appliances',
    'home appliances': 'home appliances',
    'gear': 'gaming gear',
    'gaming gear': 'gaming gear',
    'gaming': 'gaming gear'
  }
};
