import mongoose from 'mongoose';
import dotenv from 'dotenv';
import { User, Category, Product } from './models/index.js';

dotenv.config({ path: '.env.local' });

const MONGODB_URI = process.env.MONGODB_URI;

// USD to INR conversion rate (approximate)
const USD_TO_INR = 83;

const categories = [
  {
    name: 'Electronics',
    description: 'Latest gadgets, smartphones, laptops, audio devices, and electronic accessories',
    slug: 'electronics',
    image: 'https://images.unsplash.com/photo-1498049794561-7780e7231661?w=400'
  },
  {
    name: 'Clothing',
    description: 'Trendy fashion apparel, ethnic wear, western wear, and accessories for men, women & kids',
    slug: 'clothing',
    image: 'https://images.unsplash.com/photo-1445205170230-053b83016050?w=400'
  },
  {
    name: 'Home & Kitchen',
    description: 'Furniture, kitchen appliances, home decor, and lifestyle essentials',
    slug: 'home-kitchen',
    image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400'
  },
  {
    name: 'Books',
    description: 'Bestsellers, academic books, fiction, non-fiction, and children\'s books',
    slug: 'books',
    image: 'https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=400'
  },
  {
    name: 'Sports & Outdoors',
    description: 'Sports equipment, fitness gear, camping accessories, and outdoor adventure essentials',
    slug: 'sports-outdoors',
    image: 'https://images.unsplash.com/photo-1517466787929-bc90951d0974?w=400'
  },
  {
    name: 'Beauty & Health',
    description: 'Skincare, makeup, hair care, wellness products, and personal care essentials',
    slug: 'beauty-health',
    image: 'https://images.unsplash.com/photo-1596464716127-f2a82984de30?w=400'
  },
  // NEW CATEGORIES
  {
    name: 'Toys & Games',
    description: 'Educational toys, board games, video games, action figures, and fun activities for all ages',
    slug: 'toys-games',
    image: 'https://images.unsplash.com/photo-1558060370-d651511a4e72?w=400'
  },
  {
    name: 'Baby Products',
    description: 'Baby care essentials, diapers, feeding bottles, nursery items, and baby gear',
    slug: 'baby-products',
    image: 'https://images.unsplash.com/photo-1519689680058-324335c77eba?w=400'
  },
  {
    name: 'Automotive',
    description: 'Car accessories, bike accessories, vehicle care, and automotive electronics',
    slug: 'automotive',
    image: 'https://images.unsplash.com/photo-1449966368868-9f1af1ab77d0?w=400'
  },
  {
    name: 'Pet Supplies',
    description: 'Pet food, accessories, toys, grooming products, and pet care essentials',
    slug: 'pet-supplies',
    image: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=400'
  },
  {
    name: 'Garden & Outdoors',
    description: 'Garden tools, plants, outdoor furniture, lawn care, and gardening accessories',
    slug: 'garden-outdoors',
    image: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400'
  },
  {
    name: 'Office & Stationery',
    description: 'Office supplies, writing instruments, paper products, and desk accessories',
    slug: 'office-stationery',
    image: 'https://images.unsplash.com/photo-1497215842964-222b4bef3739?w=400'
  },
  {
    name: 'Musical Instruments',
    description: 'Guitars, keyboards, drums, microphones, and music accessories for beginners and professionals',
    slug: 'musical-instruments',
    image: 'https://images.unsplash.com/photo-1519892300165-cb5542fb47c7?w=400'
  },
];

// Convert USD price to INR
const toINR = (usdPrice) => Math.round(usdPrice * USD_TO_INR);

const products = [
  // ============ ELECTRONICS (8 products) ============
  {
    name: 'Wireless Bluetooth Headphones Pro',
    description: 'Premium noise-cancelling wireless headphones with 40-hour battery life. Features deep bass, comfortable over-ear design with memory foam cushions, built-in microphone for calls, and fast USB-C charging.',
    price: toINR(149.99),
    discountPrice: toINR(99.99),
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400',
    stock: 50,
    sku: 'ELEC-HP-001',
    rating: 4.5,
    reviews: 128,
    isFeatured: true,
    isTrending: true,
    trendingRank: 2,
    tags: ['headphones', 'wireless', 'bluetooth', 'audio', 'noise-cancelling'],
    keywords: ['wireless headphones', 'bluetooth earphones', 'noise cancelling headphones'],
    brand: 'SoundMax',
    specifications: { Battery: '40 hours', Driver: '40mm', Bluetooth: '5.3', Weight: '250g' },
    variants: [
      {
        sku: 'ELEC-HP-001-BLK',
        attributes: { Color: 'Black' },
        price: toINR(149.99),
        compareAtPrice: toINR(149.99),
        stock: 30,
        images: [{ url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400' }],
        status: 'active',
      },
      {
        sku: 'ELEC-HP-001-WHT',
        attributes: { Color: 'White' },
        price: toINR(149.99),
        compareAtPrice: toINR(149.99),
        stock: 20,
        images: [{ url: 'https://images.unsplash.com/photo-1583394838336-acd977736f90?w=400' }],
        status: 'active',
      }
    ]
  },
  {
    name: 'Smart Watch Ultra',
    description: 'Advanced smartwatch with AMOLED display, blood oxygen monitoring, GPS tracking, 7-day battery life, IP68 waterproof rating. Track your fitness, sleep, heart rate, and notifications in style.',
    price: toINR(249.99),
    discountPrice: toINR(199.99),
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400',
    stock: 35,
    sku: 'ELEC-SW-001',
    rating: 4.3,
    reviews: 89,
    isFeatured: true,
    isTrending: true,
    trendingRank: 1,
    tags: ['smartwatch', 'wearable', 'fitness', 'tech', 'gps'],
    keywords: ['smart watch', 'fitness tracker', 'wearable tech'],
    brand: 'TechWear',
    specifications: { Display: '1.5" AMOLED', Battery: '7 days', Waterproof: 'IP68', Sensors: 'HR, SpO2, GPS' },
  },
  {
    name: '4K Action Camera Adventure',
    description: 'Compact action camera with 4K 60fps video recording, waterproof to 40m without housing, built-in image stabilization, dual screens for vlogging. Perfect for adventures, travel, and sports.',
    price: toINR(399.99),
    discountPrice: toINR(299.99),
    image: 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=400',
    stock: 25,
    sku: 'ELEC-AC-001',
    rating: 4.4,
    reviews: 67,
    isFeatured: false,
    isTrending: false,
    tags: ['camera', 'action', '4k', 'waterproof', 'vlog'],
    keywords: ['action camera', '4k camera', 'sports camera', 'vlog camera'],
    brand: 'CapturePro',
    specifications: { Resolution: '4K 60fps', Waterproof: '40m', Stabilization: '6-axis', Screen: 'Front+Rear' },
  },
  {
    name: 'Portable Bluetooth Party Speaker',
    description: 'Powerful waterproof portable Bluetooth speaker with 360° surround sound, deep bass radiator, 20-hour battery life, built-in microphone, LED party lights, and rugged design for outdoor use.',
    price: toINR(79.99),
    discountPrice: toINR(59.99),
    image: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=400',
    stock: 60,
    sku: 'ELEC-SP-001',
    rating: 4.4,
    reviews: 156,
    isFeatured: true,
    isTrending: true,
    trendingRank: 3,
    tags: ['speaker', 'bluetooth', 'portable', 'audio', 'waterproof'],
    keywords: ['bluetooth speaker', 'portable speaker', 'waterproof speaker', 'party speaker'],
    brand: 'BassBoost',
    specifications: { Power: '30W', Battery: '20 hours', Waterproof: 'IPX7', Bluetooth: '5.2' },
  },
  {
    name: 'Laptop Backpack Waterproof',
    description: 'Premium waterproof laptop backpack with 35L capacity, fits up to 17" laptop, multiple compartments, USB charging port, padded shoulder straps, and anti-theft design. Ideal for travel and daily commute.',
    price: toINR(69.99),
    discountPrice: toINR(49.99),
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400',
    stock: 80,
    sku: 'ELEC-BP-001',
    rating: 4.6,
    reviews: 234,
    isFeatured: false,
    isTrending: false,
    tags: ['backpack', 'laptop', 'travel', 'waterproof', 'bags'],
    keywords: ['laptop backpack', 'travel backpack', 'waterproof backpack'],
    brand: 'TravelPro',
    specifications: { Capacity: '35L', Laptop: 'Up to 17"', Material: 'Waterproof Nylon', USB: 'Yes' },
  },
  {
    name: 'USB-C Fast Charger 65W',
    description: 'GaN 65W USB-C fast charger compatible with laptops, tablets, and smartphones. Ultra-compact design, dual ports (USB-C + USB-A), universal compatibility including MacBook, iPhone, Samsung, and more.',
    price: toINR(45.99),
    discountPrice: toINR(35.99),
    image: 'https://images.unsplash.com/photo-1583394838336-acd977736f90?w=400',
    stock: 150,
    sku: 'ELEC-CH-001',
    rating: 4.7,
    reviews: 412,
    isFeatured: false,
    isTrending: true,
    trendingRank: 5,
    tags: ['charger', 'usb-c', 'fast charging', 'gan', 'power adapter'],
    keywords: ['fast charger', 'USB C charger', 'GaN charger', 'laptop charger'],
    brand: 'PowerTech',
    specifications: { Power: '65W', Technology: 'GaN III', Ports: 'USB-C + USB-A', Compatible: 'Universal' },
  },
  {
    name: 'Wireless Earbuds Pro',
    description: 'Premium true wireless earbuds with active noise cancellation, adaptive EQ, transparency mode, 8 hours playback (32h with case), IPX5 water resistance, and comfortable ergonomic fit.',
    price: toINR(129.99),
    discountPrice: toINR(99.99),
    image: 'https://images.unsplash.com/photo-1590658268037-6bf12f032f55?w=400',
    stock: 45,
    sku: 'ELEC-EB-001',
    rating: 4.5,
    reviews: 189,
    isFeatured: true,
    isTrending: true,
    trendingRank: 4,
    tags: ['earbuds', 'wireless', 'noise cancelling', 'tws', 'audio'],
    keywords: ['wireless earbuds', 'TWS earbuds', 'noise cancelling earbuds'],
    brand: 'SoundMax',
    specifications: { Battery: '8h + 24h', ANC: 'Yes', Waterproof: 'IPX5', Driver: '12mm' },
  },
  {
    name: 'Mechanical Gaming Keyboard',
    description: 'RGB mechanical gaming keyboard with blue switches, N-key rollover, aluminum frame, detachable USB-C cable, and programmable macro keys. Perfect for gamers and typists.',
    price: toINR(89.99),
    discountPrice: toINR(69.99),
    image: 'https://images.unsplash.com/photo-1541140532154-b024d1e0c356?w=400',
    stock: 40,
    sku: 'ELEC-KB-001',
    rating: 4.3,
    reviews: 98,
    isFeatured: false,
    isTrending: false,
    tags: ['keyboard', 'gaming', 'mechanical', 'rgb', 'peripherals'],
    keywords: ['mechanical keyboard', 'gaming keyboard', 'RGB keyboard'],
    brand: 'GameMax',
    specifications: { Switches: 'Blue', Layout: 'Full-size', Backlight: 'RGB', Frame: 'Aluminum' },
  },

  // ============ CLOTHING (8 products) ============
  {
    name: 'Premium Cotton Casual T-Shirt',
    description: 'Premium 100% organic cotton t-shirt with a relaxed fit, reinforced stitching, and pre-shrunk fabric. Available in 8 vibrant colors. Perfect for everyday wear with exceptional comfort and breathability.',
    price: toINR(34.99),
    discountPrice: toINR(24.99),
    image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400',
    stock: 200,
    sku: 'CLTH-TS-001',
    rating: 4.7,
    reviews: 256,
    isFeatured: true,
    isTrending: true,
    trendingRank: 6,
    tags: ['t-shirt', 'cotton', 'casual', 'organic', 'men'],
    keywords: ['cotton t-shirt', 'casual wear', 'organic clothing'],
    brand: 'EcoWear',
    specifications: { Material: '100% Organic Cotton', Fit: 'Relaxed', Sizes: 'S-3XL', Care: 'Machine Wash' },
    variants: [
      {
        sku: 'CLTH-TS-001-BLK-M',
        attributes: { Color: 'Black', Size: 'M' },
        price: toINR(34.99),
        compareAtPrice: toINR(34.99),
        stock: 50,
        images: [{ url: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400' }],
        status: 'active',
      },
      {
        sku: 'CLTH-TS-001-BLU-M',
        attributes: { Color: 'Blue', Size: 'M' },
        price: toINR(34.99),
        compareAtPrice: toINR(34.99),
        stock: 45,
        images: [{ url: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=400' }],
        status: 'active',
      },
      {
        sku: 'CLTH-TS-001-WHT-L',
        attributes: { Color: 'White', Size: 'L' },
        price: toINR(34.99),
        compareAtPrice: toINR(34.99),
        stock: 30,
        images: [{ url: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400' }],
        status: 'active',
      }
    ]
  },
  {
    name: 'Women\'s Kurta Set Ethnic Wear',
    description: 'Elegant cotton kurta set with palazzo pants and dupatta. Features intricate embroidery work, comfortable straight cut, and vibrant colors. Perfect for festive occasions and daily wear.',
    price: toINR(59.99),
    discountPrice: toINR(44.99),
    image: 'https://images.unsplash.com/photo-1583391733956-6c782764164b?w=400',
    stock: 75,
    sku: 'CLTH-KR-001',
    rating: 4.6,
    reviews: 178,
    isFeatured: true,
    isTrending: true,
    trendingRank: 7,
    tags: ['kurta', 'ethnic', 'women', 'festival', 'traditional'],
    keywords: ['kurta set', 'ethnic wear women', 'festival dress'],
    brand: 'EthnicVibe',
    specifications: { Material: 'Cotton Blend', Set: 'Kurta + Palazzo + Dupatta', Sizes: 'S-XL', Care: 'Hand Wash' },
  },
  {
    name: 'Men\'s Slim Fit Jeans',
    description: 'Premium stretchable denim jeans with slim fit design, 5-pocket styling, and durable construction. Features comfort stretch fabric that moves with you. Available in dark blue, black, and light wash.',
    price: toINR(49.99),
    discountPrice: toINR(39.99),
    image: 'https://images.unsplash.com/photo-1542272454315-4c01d7abdf4a?w=400',
    stock: 120,
    sku: 'CLTH-JN-001',
    rating: 4.4,
    reviews: 312,
    isFeatured: false,
    isTrending: false,
    tags: ['jeans', 'men', 'denim', 'slim fit', 'casual'],
    keywords: ['men jeans', 'slim fit jeans', 'stretch denim'],
    brand: 'DenimCo',
    specifications: { Material: '98% Cotton, 2% Spandex', Fit: 'Slim', Sizes: '28-40', Color: 'Dark Blue' },
  },
  {
    name: 'Women\'s Floral Maxi Dress',
    description: 'Beautiful floral print maxi dress with flowy silhouette, adjustable waist tie, and breathable viscose fabric. Features elegant V-neck and short sleeves. Perfect for summer outings and beach vacations.',
    price: toINR(54.99),
    discountPrice: toINR(42.99),
    image: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=400',
    stock: 60,
    sku: 'CLTH-DR-001',
    rating: 4.5,
    reviews: 145,
    isFeatured: false,
    isTrending: true,
    trendingRank: 8,
    tags: ['dress', 'women', 'maxi', 'floral', 'summer'],
    keywords: ['maxi dress', 'floral dress', 'summer dress women'],
    brand: 'Fashionista',
    specifications: { Material: 'Viscose', Length: 'Maxi', Neck: 'V-Neck', Sizes: 'XS-XL' },
  },
  {
    name: 'Sports Track Suit Set',
    description: 'Complete sports track suit with zip-up jacket and matching pants. Made from moisture-wicking fabric, features zippered pockets, elastic waistband, and reflective strips for evening runs.',
    price: toINR(69.99),
    discountPrice: toINR(54.99),
    image: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=400',
    stock: 55,
    sku: 'CLTH-TS-002',
    rating: 4.3,
    reviews: 87,
    isFeatured: false,
    isTrending: false,
    tags: ['track suit', 'sports', 'fitness', 'men', 'activewear'],
    keywords: ['track suit', 'sports wear', 'jogger set'],
    brand: 'ActiveGear',
    specifications: { Material: 'Polyester Blend', Set: 'Jacket + Pants', Sizes: 'M-3XL', Features: 'Reflective' },
  },
  {
    name: 'Kids Cartoon Printed T-Shirt Pack',
    description: 'Pack of 5 colorful cartoon printed t-shirts for kids. Made from soft cotton jersey, pre-washed for extra comfort, and durable double-stitched seams. Available for ages 2-12 years.',
    price: toINR(39.99),
    discountPrice: toINR(29.99),
    image: 'https://images.unsplash.com/photo-1622290291468-a28f7a7dc6a8?w=400',
    stock: 100,
    sku: 'CLTH-KD-001',
    rating: 4.8,
    reviews: 201,
    isFeatured: false,
    isTrending: true,
    trendingRank: 9,
    tags: ['kids', 't-shirt', 'cotton', 'pack', 'cartoon'],
    keywords: ['kids t-shirt', 'children clothing', 'cartoon t-shirt'],
    brand: 'TinyToes',
    specifications: { Material: '100% Cotton', Pack: '5 T-shirts', Ages: '2-12 years', Care: 'Machine Wash' },
  },
  {
    name: 'Men\'s Formal Shirt Premium',
    description: 'Wrinkle-free formal shirt with spread collar, adjustable cuffs, and slim fit design. Made from premium cotton-poly blend that stays crisp all day. Ideal for office and business meetings.',
    price: toINR(44.99),
    discountPrice: toINR(34.99),
    image: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=400',
    stock: 90,
    sku: 'CLTH-FS-001',
    rating: 4.5,
    reviews: 167,
    isFeatured: false,
    isTrending: false,
    tags: ['shirt', 'formal', 'men', 'office', 'business'],
    keywords: ['formal shirt', 'office shirt', 'business shirt'],
    brand: 'ExecutiveStyle',
    specifications: { Material: 'Cotton-Poly Blend', Fit: 'Slim', Collar: 'Spread', Sizes: '38-46' },
  },
  {
    name: 'Silk Saree Designer Collection',
    description: 'Handwoven pure silk saree with traditional zari work and embellished border. Comes with matching blouse piece. Perfect for weddings, festivals, and special occasions. Premium quality with rich finish.',
    price: toINR(199.99),
    discountPrice: toINR(149.99),
    image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=400',
    stock: 20,
    sku: 'CLTH-SR-001',
    rating: 4.9,
    reviews: 89,
    isFeatured: false,
    isTrending: true,
    trendingRank: 10,
    tags: ['saree', 'silk', 'traditional', 'wedding', 'women'],
    keywords: ['silk saree', 'designer saree', 'wedding saree'],
    brand: 'HeritageWeaves',
    specifications: { Material: 'Pure Silk', Length: '6.3m', Work: 'Zari Border', Includes: 'Blouse Piece' },
  },

  // ============ HOME & KITCHEN (7 products) ============
  {
    name: 'Stainless Steel Insulated Water Bottle',
    description: 'Double-wall vacuum insulated water bottle that keeps drinks cold for 24 hours or hot for 12 hours. BPA-free, leak-proof lid, wide mouth for ice cubes, and eco-friendly reusable design.',
    price: toINR(29.99),
    discountPrice: 0,
    image: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=400',
    stock: 150,
    sku: 'HOME-WB-001',
    rating: 4.6,
    reviews: 312,
    isFeatured: true,
    isTrending: true,
    trendingRank: 11,
    tags: ['bottle', 'stainless steel', 'eco-friendly', 'hydration', 'insulated'],
    keywords: ['water bottle', 'insulated bottle', 'reusable bottle'],
    brand: 'EcoSip',
    specifications: { Capacity: '750ml', Material: 'Stainless Steel', Insulation: '24h Cold / 12h Hot', BPA: 'Free' },
  },
  {
    name: 'Ergonomic Office Chair Mesh',
    description: 'Premium ergonomic office chair with breathable mesh back, adjustable lumbar support, 3D armrests, tilt lock mechanism, and smooth-rolling casters. Designed for 8+ hours of comfortable sitting.',
    price: toINR(449.99),
    discountPrice: toINR(379.99),
    image: 'https://images.unsplash.com/photo-1592078615290-033ee584e267?w=400',
    stock: 20,
    sku: 'HOME-CH-001',
    rating: 4.2,
    reviews: 45,
    isFeatured: false,
    isTrending: false,
    tags: ['chair', 'office', 'ergonomic', 'furniture', 'mesh'],
    keywords: ['office chair', 'ergonomic chair', 'mesh chair'],
    brand: 'ComfortPro',
    specifications: { Material: 'Mesh Back + Foam Seat', Lumbar: 'Adjustable', Armrest: '3D', Weight: '22kg' },
  },
  {
    name: 'Non-Stick Cookware Set 10-Piece',
    description: 'Complete 10-piece non-stick cookware set including fry pans, saucepans, stockpot, lids, and kitchen utensils. Granite coating for scratch resistance, even heat distribution, dishwasher safe, and stay-cool handles.',
    price: toINR(199.99),
    discountPrice: toINR(149.99),
    image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400',
    stock: 30,
    sku: 'HOME-CK-001',
    rating: 4.3,
    reviews: 94,
    isFeatured: true,
    isTrending: true,
    trendingRank: 12,
    tags: ['cookware', 'kitchen', 'non-stick', 'set', 'granite'],
    keywords: ['cookware set', 'non-stick pans', 'kitchen set'],
    brand: 'ChefMaster',
    specifications: { Pieces: '10', Material: 'Granite Coating', OvenSafe: 'Up to 180°C', Dishwasher: 'Yes' },
  },
  {
    name: 'Air Purifier HEPA Filter',
    description: 'Smart air purifier with true HEPA H13 filter, covering up to 500 sq. ft. Removes 99.97% of pollutants, dust, pollen, and smoke. Features real-time air quality monitor, auto mode, sleep mode, and smart app control.',
    price: toINR(299.99),
    discountPrice: toINR(249.99),
    image: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=400',
    stock: 25,
    sku: 'HOME-AP-001',
    rating: 4.5,
    reviews: 76,
    isFeatured: false,
    isTrending: true,
    trendingRank: 13,
    tags: ['air purifier', 'hepa', 'smart', 'home', 'air quality'],
    keywords: ['air purifier', 'HEPA filter', 'air cleaner'],
    brand: 'PureAir',
    specifications: { Coverage: '500 sq.ft', Filter: 'HEPA H13', CADR: '350 m³/h', Noise: '24-50 dB' },
  },
  {
    name: 'Smart LED Bulb Wi-Fi RGB',
    description: 'Wi-Fi enabled smart LED bulb with 16 million colors and tunable white (2700K-6500K). Compatible with Alexa and Google Home. Set schedules, timers, and scenes via app. Energy-efficient 9W (60W equivalent).',
    price: toINR(19.99),
    discountPrice: toINR(14.99),
    image: 'https://images.unsplash.com/photo-1576504732343-fc5940ea1d78?w=400',
    stock: 200,
    sku: 'HOME-LB-001',
    rating: 4.4,
    reviews: 523,
    isFeatured: false,
    isTrending: false,
    tags: ['smart bulb', 'wifi', 'led', 'rgb', 'home automation'],
    keywords: ['smart bulb', 'WiFi LED bulb', 'Alexa bulb', 'RGB bulb'],
    brand: 'SmartGlow',
    specifications: { Power: '9W (60W equiv)', Color: '16M + Tunable White', Connectivity: 'Wi-Fi 2.4GHz', Voice: 'Alexa, Google' },
  },
  {
    name: 'Kitchen Trolley Storage Cart',
    description: 'Multi-functional kitchen trolley cart with 3-tier storage, bamboo shelves, locking casters wheels for mobility. Perfect for organizing spices, utensils, fruits, and vegetables. Rust-resistant frame.',
    price: toINR(89.99),
    discountPrice: toINR(69.99),
    image: 'https://images.unsplash.com/photo-1590794056226-79ef3a8147e1?w=400',
    stock: 40,
    sku: 'HOME-KT-001',
    rating: 4.5,
    reviews: 134,
    isFeatured: false,
    isTrending: false,
    tags: ['kitchen cart', 'trolley', 'storage', 'organization', 'bamboo'],
    keywords: ['kitchen trolley', 'storage cart', 'kitchen organizer'],
    brand: 'SpaceMax',
    specifications: { Tiers: '3', Material: 'Bamboo + Steel', Wheels: '4 Locking Casters', Weight: '8kg' },
  },
  {
    name: 'Electric Kettle Stainless Steel',
    description: '1.5L fast-boil electric kettle with 1500W power, stainless steel body with BPA-free interior, auto shut-off, boil-dry protection, and concealed heating element. Beautiful brushed finish with blue LED indicator.',
    price: toINR(34.99),
    discountPrice: toINR(27.99),
    image: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=400',
    stock: 85,
    sku: 'HOME-EK-001',
    rating: 4.6,
    reviews: 298,
    isFeatured: false,
    isTrending: true,
    trendingRank: 14,
    tags: ['kettle', 'electric', 'kitchen', 'appliance', 'stainless steel'],
    keywords: ['electric kettle', 'water heater', 'kitchen appliance'],
    brand: 'QuickBoil',
    specifications: { Capacity: '1.5L', Power: '1500W', Material: 'Stainless Steel', Safety: 'Auto Shut-off' },
  },

  // ============ BOOKS (6 products) ============
  {
    name: 'JavaScript: The Definitive Guide',
    description: 'The most comprehensive JavaScript reference book by David Flanagan. Covers ES2023, Node.js, modern frameworks, async programming, and best practices. Essential for every web developer from beginner to advanced.',
    price: toINR(44.99),
    discountPrice: toINR(34.99),
    image: 'https://images.unsplash.com/photo-1532012197267-da84d127e765?w=400',
    stock: 100,
    sku: 'BOOK-JS-001',
    rating: 4.8,
    reviews: 423,
    isFeatured: true,
    isTrending: true,
    trendingRank: 15,
    tags: ['book', 'javascript', 'programming', 'tech', 'web development'],
    keywords: ['javascript book', 'programming book', 'web development'],
    brand: 'O\'Reilly',
    specifications: { Author: 'David Flanagan', Pages: '720', Edition: '7th', Format: 'Paperback' },
  },
  {
    name: 'The Art of Programming',
    description: 'A masterpiece by Donald Knuth covering fundamental algorithms, data structures, and computational methods. Multi-volume set considered the bible of computer science. In-depth analysis with mathematical rigor.',
    price: toINR(89.99),
    discountPrice: toINR(69.99),
    image: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400',
    stock: 30,
    sku: 'BOOK-CS-001',
    rating: 4.9,
    reviews: 156,
    isFeatured: false,
    isTrending: false,
    tags: ['book', 'algorithms', 'programming', 'computer science', 'classic'],
    keywords: ['algorithms book', 'computer science', 'programming classics'],
    brand: 'Addison-Wesley',
    specifications: { Author: 'Donald Knuth', Volumes: '4', Pages: '3,168', Format: 'Box Set' },
  },
  {
    name: 'Rich Dad Poor Dad',
    description: 'The #1 personal finance book of all time by Robert Kiyosaki. Learn the secrets to financial freedom, investing strategies, and how to make money work for you. Updated edition with modern financial insights.',
    price: toINR(19.99),
    discountPrice: toINR(14.99),
    image: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400',
    stock: 200,
    sku: 'BOOK-PF-001',
    rating: 4.6,
    reviews: 1205,
    isFeatured: true,
    isTrending: true,
    trendingRank: 16,
    tags: ['book', 'finance', 'investing', 'self-help', 'bestseller'],
    keywords: ['rich dad poor dad', 'personal finance book', 'investing book'],
    brand: 'Plata Publishing',
    specifications: { Author: 'Robert Kiyosaki', Pages: '336', Edition: 'Updated', Format: 'Paperback' },
  },
  {
    name: 'The Psychology of Money',
    description: 'Morgan Housel explores the strange ways people think about money and how to make better financial decisions. Bestselling book that reveals timeless lessons on wealth, greed, and happiness through engaging stories.',
    price: toINR(24.99),
    discountPrice: toINR(19.99),
    image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400',
    stock: 180,
    sku: 'BOOK-PF-002',
    rating: 4.7,
    reviews: 876,
    isFeatured: false,
    isTrending: true,
    trendingRank: 17,
    tags: ['book', 'finance', 'psychology', 'money', 'bestseller'],
    keywords: ['psychology of money', 'financial psychology', 'money management'],
    brand: 'Harriman House',
    specifications: { Author: 'Morgan Housel', Pages: '256', Format: 'Hardcover', ISBN: '978-0857197689' },
  },
  {
    name: 'Atomic Habits',
    description: 'The groundbreaking book by James Clear on how tiny changes lead to remarkable results. Learn how to build good habits, break bad ones, and master the art of continuous improvement. A New York Times #1 bestseller.',
    price: toINR(22.99),
    discountPrice: toINR(17.99),
    image: 'https://images.unsplash.com/photo-1589998059171-988d887df646?w=400',
    stock: 250,
    sku: 'BOOK-SH-001',
    rating: 4.8,
    reviews: 2341,
    isFeatured: true,
    isTrending: true,
    trendingRank: 18,
    tags: ['book', 'self-help', 'habits', 'psychology', 'bestseller'],
    keywords: ['atomic habits', 'self improvement book', 'habit building'],
    brand: 'Penguin Random House',
    specifications: { Author: 'James Clear', Pages: '320', Format: 'Paperback', ISBN: '978-0735211292' },
  },
  {
    name: 'Children\'s Encyclopedia Collection',
    description: 'Set of 5 illustrated encyclopedias for curious young minds covering science, history, space, animals, and the human body. Vibrant visuals, fun facts, and age-appropriate content for children aged 6-14.',
    price: toINR(49.99),
    discountPrice: toINR(39.99),
    image: 'https://images.unsplash.com/photo-1550399105-c4db5fb85c18?w=400',
    stock: 60,
    sku: 'BOOK-CE-001',
    rating: 4.7,
    reviews: 187,
    isFeatured: false,
    isTrending: false,
    tags: ['book', 'children', 'encyclopedia', 'education', 'set'],
    keywords: ['children encyclopedia', 'kids knowledge books', 'educational books'],
    brand: 'DK Publishing',
    specifications: { Set: '5 Books', Ages: '6-14', Pages: '1,200 Total', Format: 'Hardcover' },
  },

  // ============ SPORTS & OUTDOORS (6 products) ============
  {
    name: 'Premium Yoga Mat Extra Thick',
    description: 'Extra thick 8mm non-slip yoga mat with precise alignment lines. Made from eco-friendly TPE material, includes carrying strap and yoga block. Perfect for yoga, pilates, meditation, and floor exercises.',
    price: toINR(49.99),
    discountPrice: toINR(39.99),
    image: 'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=400',
    stock: 80,
    sku: 'SPRT-YM-001',
    rating: 4.5,
    reviews: 189,
    isFeatured: true,
    isTrending: true,
    trendingRank: 19,
    tags: ['yoga', 'mat', 'fitness', 'exercise', 'pilates'],
    keywords: ['yoga mat', 'exercise mat', 'fitness mat', 'pilates mat'],
    brand: 'ZenFit',
    specifications: { Thickness: '8mm', Material: 'TPE Eco-Friendly', Size: '183x61cm', Weight: '1.2kg' },
  },
  {
    name: 'Running Shoes Pro Max',
    description: 'Lightweight professional running shoes with responsive Nike React foam cushioning, breathable Flyknit upper, rubber outsole for traction, and reflective elements for night runs. Engineered for marathon comfort.',
    price: toINR(129.99),
    discountPrice: toINR(99.99),
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400',
    stock: 45,
    sku: 'SPRT-RS-001',
    rating: 4.7,
    reviews: 201,
    isFeatured: true,
    isTrending: true,
    trendingRank: 20,
    tags: ['shoes', 'running', 'fitness', 'sports', 'marathon'],
    keywords: ['running shoes', 'sneakers', 'athletic shoes'],
    brand: 'SpeedUp',
    specifications: { Cushioning: 'React Foam', Upper: 'Flyknit Mesh', Drop: '10mm', Weight: '240g' },
  },
  {
    name: 'Adjustable Dumbbell Set 20kg',
    description: 'Space-saving adjustable dumbbell set from 2kg to 20kg each (40kg total). Quick-change weight selection system with secure locking. Includes sturdy storage tray. Perfect for home gym strength training.',
    price: toINR(249.99),
    discountPrice: toINR(199.99),
    image: 'https://images.unsplash.com/photo-1638536532686-d610adfc8e5c?w=400',
    stock: 25,
    sku: 'SPRT-DB-001',
    rating: 4.6,
    reviews: 134,
    isFeatured: false,
    isTrending: true,
    trendingRank: 21,
    tags: ['dumbbells', 'fitness', 'strength training', 'home gym', 'weights'],
    keywords: ['adjustable dumbbells', 'home gym weights', 'strength training'],
    brand: 'IronFit',
    specifications: { Weight: '2-20kg per dumbbell', Material: 'Steel + Rubber', Increments: '2kg', Storage: 'Tray Included' },
  },
  {
    name: 'Camping Tent 4-Person Waterproof',
    description: 'Spacious 4-person dome tent with waterproof rainfly, sealed seams, and bathtub floor. Easy setup with color-coded poles, mesh windows for ventilation, and storage pockets. Includes carry bag for portability.',
    price: toINR(179.99),
    discountPrice: toINR(149.99),
    image: 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=400',
    stock: 20,
    sku: 'SPRT-CT-001',
    rating: 4.4,
    reviews: 89,
    isFeatured: false,
    isTrending: false,
    tags: ['tent', 'camping', 'outdoor', 'waterproof', 'adventure'],
    keywords: ['camping tent', 'family tent', 'waterproof tent'],
    brand: 'OutdoorBase',
    specifications: { Capacity: '4 Person', Waterproof: '3000mm', Weight: '6.5kg', Setup: '2-Pole Dome' },
  },
  {
    name: 'Mountain Bike 21-Speed',
    description: 'All-terrain mountain bike with 21-speed Shimano gears, dual disc brakes, front suspension, and lightweight aluminum frame. 26-inch wheels with knobby tires for excellent grip on trails and city streets.',
    price: toINR(499.99),
    discountPrice: toINR(399.99),
    image: 'https://images.unsplash.com/photo-1576435728678-68d0fbf94e4e?w=400',
    stock: 15,
    sku: 'SPRT-BK-001',
    rating: 4.3,
    reviews: 67,
    isFeatured: false,
    isTrending: false,
    tags: ['bicycle', 'mountain bike', 'cycling', 'outdoor', 'fitness'],
    keywords: ['mountain bike', 'MTB', 'cycle for men'],
    brand: 'TrailBlazer',
    specifications: { Speeds: '21-Speed Shimano', Brakes: 'Dual Disc', Frame: 'Aluminum Alloy', Wheels: '26"' },
  },
  {
    name: 'Cricket Bat English Willow',
    description: 'Professional grade English willow cricket bat with pressed toe protection and ergonomic handle. Grade 1 willow with sweet spot optimized for power hitting. Includes bat cover. Available in sizes SH to Full.',
    price: toINR(149.99),
    discountPrice: toINR(119.99),
    image: 'https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=400',
    stock: 35,
    sku: 'SPRT-CB-001',
    rating: 4.5,
    reviews: 98,
    isFeatured: false,
    isTrending: false,
    tags: ['cricket', 'bat', 'sports', 'english willow', 'professional'],
    keywords: ['cricket bat', 'English willow bat', 'professional cricket'],
    brand: 'HitZone',
    specifications: { Willow: 'English Grade 1', Sizes: 'SH to Full', Handle: 'Oval with Grip', Protection: 'Toe Guard' },
  },

  // ============ BEAUTY & HEALTH (7 products) ============
  {
    name: 'Vitamin C Face Serum with Hyaluronic Acid',
    description: 'Advanced vitamin C face serum with 20% L-Ascorbic Acid and hyaluronic acid. Brightens skin, reduces dark spots and fine lines, provides deep hydration. 100% natural ingredients, dermatologist tested, suitable for all skin types.',
    price: toINR(39.99),
    discountPrice: toINR(29.99),
    image: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400',
    stock: 120,
    sku: 'BEAUTY-FS-001',
    rating: 4.6,
    reviews: 278,
    isFeatured: true,
    isTrending: true,
    trendingRank: 22,
    tags: ['skincare', 'serum', 'beauty', 'vitamin c', 'anti-aging'],
    keywords: ['face serum', 'vitamin c serum', 'skincare', 'anti aging'],
    brand: 'GlowLab',
    specifications: { Active: '20% Vitamin C', Size: '30ml', SkinType: 'All', Tested: 'Dermatologist' },
  },
  {
    name: 'Hair Oil Ayurvedic Treatment',
    description: 'Traditional Ayurvedic hair oil blend of bhringraj, amla, coconut, almond, and essential oils. Promotes hair growth, reduces hair fall, prevents premature graying, and nourishes scalp. 100% natural, no chemicals.',
    price: toINR(24.99),
    discountPrice: toINR(19.99),
    image: 'https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=400',
    stock: 95,
    sku: 'BEAUTY-HO-001',
    rating: 4.7,
    reviews: 412,
    isFeatured: true,
    isTrending: true,
    trendingRank: 23,
    tags: ['hair oil', 'ayurvedic', 'hair care', 'natural', 'beauty'],
    keywords: ['hair oil', 'ayurvedic hair oil', 'hair growth oil'],
    brand: 'HeritageAyur',
    specifications: { Size: '200ml', Base: 'Coconut + Almond', Active: 'Bhringraj + Amla', Natural: '100% Chemical Free' },
  },
  {
    name: 'Sunscreen SPF 50+ Matte Finish',
    description: 'Ultra-light sunscreen with SPF 50+ PA+++ broad spectrum protection. Non-greasy matte finish with zero white cast. Enriched with aloe vera and vitamin E. Water resistant for 80 minutes. Perfect for Indian weather.',
    price: toINR(19.99),
    discountPrice: toINR(14.99),
    image: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=400',
    stock: 180,
    sku: 'BEAUTY-SS-001',
    rating: 4.5,
    reviews: 567,
    isFeatured: false,
    isTrending: true,
    trendingRank: 24,
    tags: ['sunscreen', 'spf', 'skincare', 'sun protection', 'matte'],
    keywords: ['sunscreen', 'sunblock', 'SPF 50', 'matte sunscreen'],
    brand: 'SunShield',
    specifications: { SPF: '50+ PA+++', Size: '50ml', Finish: 'Matte', WaterResistant: '80 minutes' },
  },
  {
    name: 'Professional Hair Dryer 2000W',
    description: 'Salon-grade hair dryer with 2000W professional AC motor, ionic technology for frizz-free shine, 3 heat + 2 speed settings, cool shot button, concentrator and diffuser attachments. Lightweight and ergonomic.',
    price: toINR(59.99),
    discountPrice: toINR(44.99),
    image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=400',
    stock: 40,
    sku: 'BEAUTY-HD-001',
    rating: 4.4,
    reviews: 167,
    isFeatured: false,
    isTrending: false,
    tags: ['hair dryer', 'beauty', 'hair care', 'salon', 'professional'],
    keywords: ['hair dryer', 'blow dryer', 'professional hair dryer'],
    brand: 'StylePro',
    specifications: { Power: '2000W', Motor: 'AC Professional', Ionic: 'Yes', Attachments: 'Concentrator + Diffuser' },
  },
  {
    name: 'Men\'s Face Wash Charcoal',
    description: 'Deep cleansing face wash with activated charcoal and tea tree oil for men. Removes excess oil, unclogs pores, prevents acne and blackheads. Refreshing menthol feel. Suitable for oily and combination skin.',
    price: toINR(14.99),
    discountPrice: toINR(11.99),
    image: 'https://images.unsplash.com/photo-1596755389378-c31d21fd1273?w=400',
    stock: 150,
    sku: 'BEAUTY-FW-001',
    rating: 4.5,
    reviews: 345,
    isFeatured: false,
    isTrending: true,
    trendingRank: 25,
    tags: ['face wash', 'men', 'skincare', 'charcoal', 'acne'],
    keywords: ['men face wash', 'charcoal face wash', 'acne face wash'],
    brand: 'MantraMen',
    specifications: { Size: '100ml', Active: 'Charcoal + Tea Tree', SkinType: 'Oily/Combination', Features: 'Menthol Fresh' },
  },
  {
    name: 'Organic Green Tea Detox Pack',
    description: 'Premium organic green tea sourced from Darjeeling gardens. Rich in antioxidants, boosts metabolism, improves focus, and supports immune health. Pack of 100 tea bags in eco-friendly packaging.',
    price: toINR(18.99),
    discountPrice: toINR(14.99),
    image: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400',
    stock: 200,
    sku: 'BEAUTY-GT-001',
    rating: 4.6,
    reviews: 678,
    isFeatured: false,
    isTrending: false,
    tags: ['green tea', 'health', 'organic', 'wellness', 'detox'],
    keywords: ['green tea', 'organic tea', 'detox tea', 'wellness'],
    brand: 'PureLeaf',
    specifications: { Quantity: '100 Tea Bags', Type: 'Organic Darjeeling', Caffeine: 'Natural', Packaging: 'Eco-Friendly' },
  },
  {
    name: 'Lip Balm Set Tinted Collection',
    description: 'Set of 6 tinted lip balms with shea butter, coconut oil, and vitamin E. Natural colors for a subtle tint with moisturizing care. SPF 15 protection, no parabens or sulfates. Perfect everyday lip care.',
    price: toINR(24.99),
    discountPrice: toINR(19.99),
    image: 'https://images.unsplash.com/photo-1617897903246-719242758050?w=400',
    stock: 130,
    sku: 'BEAUTY-LB-001',
    rating: 4.4,
    reviews: 234,
    isFeatured: false,
    isTrending: false,
    tags: ['lip balm', 'beauty', 'makeup', 'tinted', 'skincare'],
    keywords: ['lip balm set', 'tinted lip balm', 'natural lip care'],
    brand: 'KissSoft',
    specifications: { Pack: '6 Balms', Base: 'Shea + Coconut', SPF: '15', Natural: 'Paraben Free' },
  },

  // ============ TOYS & GAMES (7 products) ============
  {
    name: 'Remote Control Racing Car',
    description: 'High-speed RC racing car with rechargeable battery, 2.4GHz remote control, and durable shockproof body. Reaches speeds up to 30km/h with 30-minute runtime. Perfect for kids aged 8+.',
    price: toINR(49.99), discountPrice: toINR(39.99), image: 'https://images.unsplash.com/photo-1594787318286-3d835c1d207f?w=400',
    stock: 40, sku: 'TOYS-RC-001', rating: 4.3, reviews: 87, isFeatured: true, isTrending: true, trendingRank: 26,
    tags: ['rc car', 'remote control', 'toys', 'racing', 'kids'],
    keywords: ['remote control car', 'RC toy', 'racing car toy'],
    brand: 'SpeedToys', specifications: { Speed: '30 km/h', Battery: 'Rechargeable', Range: '50m', Age: '8+' },
  },
  {
    name: 'Board Game Collection Premium Set',
    description: 'Premium 12-in-1 board game set including Chess, Ludo, Snakes & Ladders, Carrom, Checkers, and more. Foldable board with storage compartment for pieces. Ideal for family game nights.',
    price: toINR(34.99), discountPrice: toINR(27.99), image: 'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=400',
    stock: 60, sku: 'TOYS-BG-001', rating: 4.6, reviews: 145, isFeatured: true, isTrending: true, trendingRank: 27,
    tags: ['board game', 'family game', 'chess', 'carrom', 'indoor games'],
    keywords: ['board game set', 'family board games', 'indoor games'],
    brand: 'FunBoard', specifications: { Games: '12-in-1', Material: 'Wooden Board', Players: '2-4', Age: '4+' },
  },
  {
    name: 'Lego Style Building Blocks Set 500pc',
    description: 'Creative building blocks set with 500 colorful pieces in various shapes and sizes. Compatible with all major brands. Includes storage box, base plates, and idea booklet for endless creativity.',
    price: toINR(29.99), discountPrice: toINR(24.99), image: 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=400',
    stock: 80, sku: 'TOYS-BB-001', rating: 4.7, reviews: 234, isFeatured: false, isTrending: true, trendingRank: 28,
    tags: ['building blocks', 'construction toys', 'creative play', 'educational'],
    keywords: ['building blocks', 'construction set', 'educational toys'],
    brand: 'BuildFun', specifications: { Pieces: '500', Material: 'Non-Toxic ABS', Compatible: 'Universal', Age: '3+' },
  },
  {
    name: 'Educational Science Kit for Kids',
    description: 'Complete STEM science kit with 50+ experiments including volcano eruption, crystal growing, slime making, and magnetic activities. Includes all chemicals, equipment, and colorful instruction manual.',
    price: toINR(39.99), discountPrice: toINR(32.99), image: 'https://images.unsplash.com/photo-1567427017947-545c5f8d16ad?w=400',
    stock: 35, sku: 'TOYS-SK-001', rating: 4.5, reviews: 98, isFeatured: false, isTrending: false,
    tags: ['science kit', 'stem', 'educational', 'experiments', 'kids learning'],
    keywords: ['science kit', 'STEM toys', 'educational kit kids'],
    brand: 'EduLab', specifications: { Experiments: '50+', Age: '6-12', Includes: 'Chemicals + Equipment', Guide: 'Color Manual' },
  },
  {
    name: 'Remote Control Drone with Camera',
    description: 'Foldable RC drone with HD 1080p camera, altitude hold, one-key takeoff/landing, and 360° flip. 15-minute flight time with 100m range. Great for beginners and hobbyists.',
    price: toINR(89.99), discountPrice: toINR(69.99), image: 'https://images.unsplash.com/photo-1507582020474-9a35b7d455d9?w=400',
    stock: 20, sku: 'TOYS-DR-001', rating: 4.2, reviews: 56, isFeatured: false, isTrending: false,
    tags: ['drone', 'remote control', 'camera', 'flying toy', 'electronics'],
    keywords: ['drone for kids', 'RC drone', 'camera drone'],
    brand: 'SkyFly', specifications: { Camera: '1080p HD', FlightTime: '15 min', Range: '100m', Battery: '3.7V LiPo' },
  },
  {
    name: 'Soft Plush Teddy Bear Giant 36"',
    description: 'Extra-large 36-inch super soft plush teddy bear with premium PP cotton filling, embroidered eyes for safety, and washable surface. Perfect gift for birthdays, valentine, or any occasion.',
    price: toINR(44.99), discountPrice: toINR(36.99), image: 'https://images.unsplash.com/photo-1567515002184-21904a6e3b3a?w=400',
    stock: 25, sku: 'TOYS-TB-001', rating: 4.8, reviews: 312, isFeatured: true, isTrending: true, trendingRank: 29,
    tags: ['teddy bear', 'plush toy', 'soft toy', 'gift', 'giant bear'],
    keywords: ['giant teddy bear', 'soft toy', 'plush bear gift'],
    brand: 'CuddleSoft', specifications: { Size: '36 inches', Material: 'Premium PP Cotton', Surface: 'Minky Fabric', Age: 'All Ages' },
  },
  {
    name: 'Action Figure Superhero Collection Set',
    description: 'Set of 6 detailed action figures with movable joints, accessories, and display stands. Each figure stands 6 inches tall with authentic movie-inspired designs. Collector grade quality.',
    price: toINR(54.99), discountPrice: toINR(44.99), image: 'https://images.unsplash.com/photo-1608889825205-e3d14b42af79?w=400',
    stock: 30, sku: 'TOYS-AF-001', rating: 4.4, reviews: 78, isFeatured: false, isTrending: false,
    tags: ['action figures', 'superhero', 'collectibles', 'toys', 'gaming'],
    keywords: ['action figures set', 'superhero toys', 'collectible figures'],
    brand: 'HeroCraft', specifications: { Set: '6 Figures', Height: '6 inches', Material: 'PVC + ABS', Articulation: '14 Points' },
  },

  // ============ BABY PRODUCTS (7 products) ============
  {
    name: 'Baby Diaper Premium Pack (72 Count)',
    description: 'Ultra-soft premium baby diapers with 12-hour leak protection, wetness indicator, and hypoallergenic materials. Size NB, S, M, L, XL available. Dermatologist tested and pediatrician recommended.',
    price: toINR(29.99), discountPrice: toINR(24.99), image: 'https://images.unsplash.com/photo-1584828284968-3b757ecb1024?w=400',
    stock: 200, sku: 'BABY-DP-001', rating: 4.6, reviews: 567, isFeatured: true, isTrending: true, trendingRank: 30,
    tags: ['diapers', 'baby care', 'newborn', 'nappies', 'baby essentials'],
    keywords: ['baby diapers', 'premium nappies', 'newborn care'],
    brand: 'SoftCare', specifications: { Count: '72 Diapers', Sizes: 'NB-XL', Leakage: '12 Hours', Material: 'Hypoallergenic' },
  },
  {
    name: 'Baby Feeding Bottle Set Anti-Colic',
    description: 'Complete set of 3 anti-colic baby feeding bottles (150ml + 240ml + 300ml) with natural feel nipples, BPA-free material, and ergonomic design. Suitable from 0+ months. Dishwasher and sterilizer safe.',
    price: toINR(24.99), discountPrice: toINR(19.99), image: 'https://images.unsplash.com/photo-1622286342621-4bd786c2447c?w=400',
    stock: 100, sku: 'BABY-FB-001', rating: 4.5, reviews: 234, isFeatured: true, isTrending: true, trendingRank: 31,
    tags: ['feeding bottle', 'baby feeding', 'newborn', 'anti-colic', 'baby essentials'],
    keywords: ['baby feeding bottles', 'anti-colic bottles', 'newborn feeding'],
    brand: 'BabyFeel', specifications: { Set: '3 Bottles', Sizes: '150+240+300ml', Material: 'BPA-Free', Flow: 'Slow-Medium-Fast' },
  },
  {
    name: 'Baby Wipes Organic Aloe Vera (12 Pack)',
    description: 'Pack of 12 organic bamboo baby wipes with natural aloe vera and chamomile extract. 99% water, alcohol-free, fragrance-free, and hypoallergenic. Extra thick and gentle for sensitive newborn skin.',
    price: toINR(19.99), discountPrice: toINR(15.99), image: 'https://images.unsplash.com/photo-1613514785940-daed07799d9b?w=400',
    stock: 150, sku: 'BABY-WP-001', rating: 4.7, reviews: 412, isFeatured: false, isTrending: false,
    tags: ['baby wipes', 'organic', 'baby care', 'newborn', 'hypoallergenic'],
    keywords: ['baby wipes pack', 'organic wipes', 'newborn wipes'],
    brand: 'EcoBaby', specifications: { Pack: '12 x 80 Wipes', Material: 'Bamboo Fiber', Additives: 'Aloe + Chamomile', Alcohol: 'Free' },
  },
  {
    name: 'Baby Stroller Lightweight Foldable',
    description: 'Ultra-lightweight aluminum baby stroller weighing only 5.5kg. One-hand fold mechanism, reclining seat, adjustable canopy, 5-point safety harness, and large storage basket. Suitable from 6 months to 3 years.',
    price: toINR(199.99), discountPrice: toINR(159.99), image: 'https://images.unsplash.com/photo-1591871937573-74d2y797?w=400',
    stock: 15, sku: 'BABY-ST-001', rating: 4.4, reviews: 67, isFeatured: false, isTrending: true, trendingRank: 32,
    tags: ['stroller', 'baby walk', 'baby gear', 'foldable', 'lightweight'],
    keywords: ['baby stroller', 'lightweight pram', 'foldable baby carriage'],
    brand: 'EasyGo', specifications: { Weight: '5.5 kg', Age: '6-36 months', Fold: 'One-hand', Harness: '5-point' },
  },
  {
    name: 'Baby Musical Mobile Crib Toy',
    description: 'Musical mobile with 4 soft plush toys, soothing melodies, nature sounds, and soft LED star projector. Rotates 360° with adjustable volume. Detachable toys can be used as rattles. Batteries included.',
    price: toINR(39.99), discountPrice: toINR(32.99), image: 'https://images.unsplash.com/photo-1556370058-3b3738a4f9c1?w=400',
    stock: 45, sku: 'BABY-MB-001', rating: 4.5, reviews: 123, isFeatured: false, isTrending: false,
    tags: ['baby mobile', 'crib toy', 'musical toy', 'newborn gift', 'baby room'],
    keywords: ['baby mobile', 'crib musical toy', 'newborn gift set'],
    brand: 'SleepyStar', specifications: { Sounds: '30 Melodies', Projection: 'LED Stars', Plush: '4 Toys', Age: '0-12 months' },
  },
  {
    name: 'Baby Care Essentials Gift Set',
    description: 'Complete baby gift set including lotion, shampoo, body wash, diaper cream, baby oil, and powder. All products are natural, paraben-free, and dermatologist tested. Packed in a beautiful gift box.',
    price: toINR(34.99), discountPrice: toINR(27.99), image: 'https://images.unsplash.com/photo-1526948128573-703ee1aeb6fa?w=400',
    stock: 50, sku: 'BABY-GF-001', rating: 4.6, reviews: 189, isFeatured: true, isTrending: false,
    tags: ['baby gift set', 'baby care', 'newborn essentials', 'gift box'],
    keywords: ['baby gift set', 'newborn care kit', 'baby essentials'],
    brand: 'GentleBaby', specifications: { Pieces: '6', Type: 'Lotion + Shampoo + Wash + Cream + Oil + Powder', Natural: 'Yes', Paraben: 'Free' },
  },
  {
    name: 'Baby Walker with Activity Center',
    description: 'Interactive baby walker with musical activity center, lights, sounds, and detachable toys. Adjustable height with 3 positions, safety brakes, and non-slip wheels. Helps babies learn to walk with fun.',
    price: toINR(69.99), discountPrice: toINR(54.99), image: 'https://images.unsplash.com/photo-1595815774280-3e8551C2e7b9?w=400',
    stock: 20, sku: 'BABY-WK-001', rating: 4.3, reviews: 89, isFeatured: false, isTrending: false,
    tags: ['baby walker', 'activity center', 'learning toy', 'baby gear'],
    keywords: ['baby walker', 'activity walker', 'learning walker'],
    brand: 'LearnFun', specifications: { Age: '6-18 months', Height: '3 Adjustable', Safety: 'Brakes + Non-slip', Activities: 'Music + Lights + Sounds' },
  },

  // ============ AUTOMOTIVE (7 products) ============
  {
    name: 'Car Dashboard Phone Mount',
    description: 'Universal car dashboard phone mount with strong suction cup, 360° rotation, and one-touch release. Compatible with all smartphones up to 6.9 inches. Vibration dampening for smooth viewing.',
    price: toINR(19.99), discountPrice: toINR(14.99), image: 'https://images.unsplash.com/photo-1585399000684-d2f72660f092?w=400',
    stock: 120, sku: 'AUTO-PM-001', rating: 4.5, reviews: 543, isFeatured: true, isTrending: true, trendingRank: 33,
    tags: ['phone mount', 'car accessory', 'dashboard', 'driving', 'gps holder'],
    keywords: ['car phone mount', 'dashboard holder', 'phone stand car'],
    brand: 'DriveMate', specifications: { Compatibility: 'Up to 6.9" phones', Mount: 'Suction Cup', Rotation: '360°', Material: 'ABS + Silicone' },
  },
  {
    name: 'Car Seat Cover Set Premium Leather',
    description: 'Premium synthetic leather car seat cover set for front and rear seats. Universal fit for most cars, easy installation with elastic straps, breathable design, and anti-slip backing. Available in 6 colors.',
    price: toINR(89.99), discountPrice: toINR(69.99), image: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=400',
    stock: 30, sku: 'AUTO-SC-001', rating: 4.3, reviews: 167, isFeatured: true, isTrending: true, trendingRank: 34,
    tags: ['seat cover', 'car interior', 'leather', 'car accessories', 'automotive'],
    keywords: ['car seat covers', 'leather seat covers', 'auto interior'],
    brand: 'AutoLux', specifications: { Material: 'PU Leather', Fit: 'Universal', Set: 'Front + Rear', Colors: '6 Options' },
  },
  {
    name: 'Tyre Inflator Portable Air Pump',
    description: 'Digital portable tyre inflator with LED display, auto shut-off at preset pressure, and 150 PSI max pressure. Includes adapters for bikes, cars, balls, and inflatables. Compact storage with carrying case.',
    price: toINR(49.99), discountPrice: toINR(39.99), image: 'https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=400',
    stock: 45, sku: 'AUTO-TI-001', rating: 4.6, reviews: 234, isFeatured: false, isTrending: true, trendingRank: 35,
    tags: ['tyre inflator', 'air pump', 'car emergency', 'portable', 'automotive tool'],
    keywords: ['portable tyre inflator', 'car air pump', 'digital inflator'],
    brand: 'AirQuick', specifications: { MaxPSI: '150 PSI', Power: '12V DC', Display: 'LED Digital', Accessories: '5 Adapters' },
  },
  {
    name: 'Car Vacuum Cleaner Handheld',
    description: 'Powerful 6000Pa handheld car vacuum cleaner with HEPA filter, USB rechargeable battery, and various nozzle attachments. Cordless design for easy cleaning of seats, floor mats, and dashboard crevices.',
    price: toINR(59.99), discountPrice: toINR(44.99), image: 'https://images.unsplash.com/photo-1624571405105-96a9ff2a27e0?w=400',
    stock: 40, sku: 'AUTO-VC-001', rating: 4.4, reviews: 189, isFeatured: false, isTrending: false,
    tags: ['car vacuum', 'handheld cleaner', 'car cleaning', 'auto accessories'],
    keywords: ['car vacuum cleaner', 'handheld vacuum', 'auto detailing'],
    brand: 'CleanDrive', specifications: { Suction: '6000Pa', Battery: '2000mAh USB-C', Runtime: '25 min', Filter: 'HEPA' },
  },
  {
    name: 'Car Sunshade Windshield Protector',
    description: 'Premium car sunshade for windshield with 5-layer reflective material. Blocks 99% of UV rays, reduces interior heat by 20°C. Foldable design with included storage pouch. Universal fit for most cars and SUVs.',
    price: toINR(24.99), discountPrice: toINR(18.99), image: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=400',
    stock: 80, sku: 'AUTO-SS-001', rating: 4.5, reviews: 312, isFeatured: false, isTrending: false,
    tags: ['sunshade', 'car protection', 'uv protection', 'windshield', 'summer accessory'],
    keywords: ['car sunshade', 'windshield protector', 'UV sun blocker'],
    brand: 'CoolCar', specifications: { Layers: '5-layer Reflective', Protection: '99% UV', HeatReduction: 'Up to 20°C', Fit: 'Universal' },
  },
  {
    name: 'Car Perfume Vent Clip Premium',
    description: 'Elegant car perfume vent clip with long-lasting fragrance (30-45 days). Premium essential oil blends including Ocean Fresh, Lavender, Citrus, and Sandalwood. Adjustable intensity control. Leak-proof design.',
    price: toINR(14.99), discountPrice: toINR(11.99), image: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=400',
    stock: 100, sku: 'AUTO-CP-001', rating: 4.3, reviews: 456, isFeatured: false, isTrending: false,
    tags: ['car perfume', 'air freshener', 'vent clip', 'car accessory', 'fragrance'],
    keywords: ['car perfume', 'air freshener vent clip', 'car fragrance'],
    brand: 'AromaDrive', specifications: { Duration: '30-45 Days', Scents: '4 Options', Material: 'ABS + Aluminum', Type: 'Essential Oil' },
  },
  {
    name: 'Car Emergency Kit Roadside Safety',
    description: 'Complete 18-piece car emergency kit including jumper cables, first aid kit, reflective triangle, tow rope, tire pressure gauge, emergency blanket, flashlight, gloves, and more. Compact storage bag included.',
    price: toINR(44.99), discountPrice: toINR(34.99), image: 'https://images.unsplash.com/photo-1607962837359-5e7e89f86776?w=400',
    stock: 35, sku: 'AUTO-EK-001', rating: 4.7, reviews: 198, isFeatured: true, isTrending: true, trendingRank: 36,
    tags: ['emergency kit', 'car safety', 'roadside kit', 'car tool', 'automotive'],
    keywords: ['car emergency kit', 'roadside assistance kit', 'safety kit'],
    brand: 'SafeRoad', specifications: { Pieces: '18', Includes: 'Jumper Cables + First Aid + Triangle', Bag: 'Storage Bag Included', Type: 'Roadside Emergency' },
  },

  // ============ PET SUPPLIES (7 products) ============
  {
    name: 'Premium Dog Food Dry Adult 5kg',
    description: 'High-protein premium dry dog food with real chicken as #1 ingredient. Contains omega-3 for coat health, glucosamine for joints, and probiotics for digestion. Complete nutrition for adult dogs 1-7 years.',
    price: toINR(44.99), discountPrice: toINR(36.99), image: 'https://images.unsplash.com/photo-1565708095953-e7958cfb5b?w=400',
    stock: 60, sku: 'PET-DF-001', rating: 4.6, reviews: 345, isFeatured: true, isTrending: true, trendingRank: 37,
    tags: ['dog food', 'pet food', 'dry food', 'dog nutrition', 'pet supplies'],
    keywords: ['premium dog food', 'dry dog food', 'adult dog nutrition'],
    brand: 'PetFit', specifications: { Weight: '5 kg', Protein: '28% Min', Age: '1-7 years', Flavor: 'Real Chicken' },
  },
  {
    name: 'Cat Tree Tower with Scratching Post',
    description: 'Multi-level cat tree tower with scratching posts, cozy condo, dangling toys, and plush perches. 160cm tall with sturdy sisal rope posts. Provides exercise, scratching, and napping space for cats.',
    price: toINR(79.99), discountPrice: toINR(62.99), image: 'https://images.unsplash.com/photo-1545249390-6bdfa286032f?w=400',
    stock: 15, sku: 'PET-CT-001', rating: 4.4, reviews: 89, isFeatured: true, isTrending: true, trendingRank: 38,
    tags: ['cat tree', 'scratching post', 'cat furniture', 'pet toy', 'cat condo'],
    keywords: ['cat tree tower', 'scratching post', 'cat furniture'],
    brand: 'CatHaven', specifications: { Height: '160 cm', Levels: '5', Material: 'Sisal + Plush', Weight: '12 kg' },
  },
  {
    name: 'Pet Grooming Kit Professional Set',
    description: 'Complete 12-piece pet grooming kit with stainless steel brush, de-shedding tool, nail clippers, comb, scissors, and more. Suitable for dogs and cats. Ergonomic handles with non-slip grips.',
    price: toINR(34.99), discountPrice: toINR(27.99), image: 'https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?w=400',
    stock: 40, sku: 'PET-GK-001', rating: 4.5, reviews: 156, isFeatured: false, isTrending: true, trendingRank: 39,
    tags: ['pet grooming', 'dog brush', 'cat brush', 'grooming kit', 'pet care'],
    keywords: ['pet grooming kit', 'dog grooming set', 'cat grooming tools'],
    brand: 'GroomPro', specifications: { Pieces: '12', Suitable: 'Dogs + Cats', Material: 'Stainless Steel', Storage: 'Carrying Case' },
  },
  {
    name: 'Pet Bed Orthopedic Memory Foam',
    description: 'Orthopedic memory foam pet bed with washable removable cover, non-slip bottom, and supportive bolsters. Provides joint relief for older pets. Available in 4 sizes from Small to X-Large. Machine washable cover.',
    price: toINR(59.99), discountPrice: toINR(47.99), image: 'https://images.unsplash.com/photo-1541443131876-44bda19923ef?w=400',
    stock: 25, sku: 'PET-PB-001', rating: 4.6, reviews: 201, isFeatured: true, isTrending: false,
    tags: ['pet bed', 'dog bed', 'cat bed', 'orthopedic', 'memory foam'],
    keywords: ['orthopedic pet bed', 'memory foam dog bed', 'pet sleeping'],
    brand: 'ComfortPet', specifications: { Sizes: 'S/M/L/XL', Fill: 'Memory Foam', Cover: 'Machine Washable', Bottom: 'Non-Slip' },
  },
  {
    name: 'Pet Water Fountain Automatic',
    description: 'Automatic pet water fountain with 2L capacity, triple filtration system, and ultra-quiet pump. Encourages pets to drink more with flowing water. BPA-free material with LED indicator for low water.',
    price: toINR(39.99), discountPrice: toINR(32.99), image: 'https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?w=400',
    stock: 30, sku: 'PET-WF-001', rating: 4.5, reviews: 178, isFeatured: false, isTrending: false,
    tags: ['pet fountain', 'water dispenser', 'cat fountain', 'dog water', 'pet accessory'],
    keywords: ['pet water fountain', 'automatic water dispenser', 'cat drinking fountain'],
    brand: 'FreshPet', specifications: { Capacity: '2L', Filtration: 'Triple Filter', Pump: 'Ultra-Quiet', Material: 'BPA-Free' },
  },
  {
    name: 'Dog Leash Retractable Heavy Duty',
    description: 'Heavy-duty retractable dog leash with 5m length, ergonomic handle with brake button, and strong nylon tape. Supports dogs up to 50kg. Reflective stitching for night walks. Durable ABS casing.',
    price: toINR(24.99), discountPrice: toINR(19.99), image: 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=400',
    stock: 55, sku: 'PET-DL-001', rating: 4.4, reviews: 234, isFeatured: false, isTrending: false,
    tags: ['dog leash', 'retractable leash', 'pet walking', 'dog accessory'],
    keywords: ['retractable dog leash', 'heavy duty leash', 'dog walking accessory'],
    brand: 'WalkEasy', specifications: { Length: '5m', MaxWeight: '50 kg', Material: 'Nylon Tape + ABS', Feature: 'Reflective + Brake' },
  },
  {
    name: 'Pet Carrier Bag Travel Backpack',
    description: 'Comfortable pet carrier backpack for small dogs and cats up to 8kg. Ventilated mesh panels, fleece bedding, safety tether, and multiple entry points. Foldable design for storage. Airline approved.',
    price: toINR(49.99), discountPrice: toINR(39.99), image: 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=400',
    stock: 20, sku: 'PET-PC-001', rating: 4.3, reviews: 87, isFeatured: false, isTrending: false,
    tags: ['pet carrier', 'pet backpack', 'travel kennel', 'dog carrier', 'cat carrier'],
    keywords: ['pet carrier backpack', 'dog travel bag', 'cat carrier bag'],
    brand: 'TravelPet', specifications: { MaxWeight: '8 kg', Material: 'Polyester + Mesh', Ventilation: '3-sided Mesh', Airline: 'Approved' },
  },

  // ============ GARDEN & OUTDOORS (7 products) ============
  {
    name: 'Garden Tool Set 12-Piece Heavy Duty',
    description: 'Complete 12-piece garden tool set with ergonomic handles including trowel, pruner, rake, shovel, hoe, weeder, gloves, and more. Carbon steel heads with rust-resistant coating. Includes storage tote bag.',
    price: toINR(49.99), discountPrice: toINR(39.99), image: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400',
    stock: 35, sku: 'GRDN-TS-001', rating: 4.5, reviews: 134, isFeatured: true, isTrending: true, trendingRank: 40,
    tags: ['garden tools', 'gardening set', 'yard tools', 'planting tools', 'gardening'],
    keywords: ['garden tool set', 'gardening kit', 'yard work tools'],
    brand: 'GreenThumb', specifications: { Pieces: '12', Handle: 'Ergonomic TPR', Head: 'Carbon Steel', Storage: 'Tote Bag Included' },
  },
  {
    name: 'Plant Pots Set Self-Watering 5-Pack',
    description: 'Set of 5 self-watering plant pots with water level indicator, 1.5L capacity each. Includes coconut coir soil discs. Built-in reservoir reduces watering frequency. Perfect for indoor plants and balcony gardens.',
    price: toINR(34.99), discountPrice: toINR(28.99), image: 'https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=400',
    stock: 50, sku: 'GRDN-PP-001', rating: 4.6, reviews: 245, isFeatured: true, isTrending: true, trendingRank: 41,
    tags: ['plant pots', 'self watering', 'indoor garden', 'balcony', 'planter'],
    keywords: ['self watering pots', 'plant containers', 'indoor planters set'],
    brand: 'GrowEasy', specifications: { Pack: '5 Pots', Capacity: '1.5L each', Material: 'PP Plastic', Color: 'Sage Green' },
  },
  {
    name: 'Outdoor String Lights LED 20m',
    description: 'Weatherproof 20m LED string lights with 100 warm white bulbs. 8 lighting modes including twinkle, fading, and steady. Suitable for garden, patio, balcony, and party decoration. Energy-efficient with timer.',
    price: toINR(29.99), discountPrice: toINR(24.99), image: 'https://images.unsplash.com/photo-1565819434352-25fc50ec3b4c?w=400',
    stock: 60, sku: 'GRDN-SL-001', rating: 4.4, reviews: 312, isFeatured: false, isTrending: true, trendingRank: 42,
    tags: ['string lights', 'outdoor lighting', 'garden lights', 'festival lights', 'LED'],
    keywords: ['LED string lights', 'garden lights', 'outdoor fairy lights'],
    brand: 'GlowGarden', specifications: { Length: '20m', Bulbs: '100 LEDs', Modes: '8', Weatherproof: 'IP44' },
  },
  {
    name: 'Automatic Garden Irrigation System',
    description: 'Complete drip irrigation kit with timer, 15m tubing, 20 drippers, connectors, and stakes. Programmable watering schedule with rain delay. Covers up to 50 plants. Easy DIY installation no tools required.',
    price: toINR(59.99), discountPrice: toINR(47.99), image: 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=400',
    stock: 20, sku: 'GRDN-IR-001', rating: 4.3, reviews: 78, isFeatured: false, isTrending: false,
    tags: ['irrigation system', 'garden watering', 'drip irrigation', 'automatic', 'plant care'],
    keywords: ['garden irrigation system', 'drip watering kit', 'automatic plant watering'],
    brand: 'WaterWise', specifications: { Coverage: '50 plants', Tubing: '15m', Timer: 'Programmable', Install: 'Tool-free' },
  },
  {
    name: 'Organic Fertilizer Plant Food 5kg',
    description: 'Premium organic fertilizer with balanced NPK 5-5-5 formula. Enriched with seaweed extract, worm castings, and beneficial microbes. Suitable for all indoor and outdoor plants. Promotes healthy growth and flowering.',
    price: toINR(24.99), discountPrice: toINR(19.99), image: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400',
    stock: 70, sku: 'GRDN-FT-001', rating: 4.5, reviews: 167, isFeatured: false, isTrending: false,
    tags: ['fertilizer', 'plant food', 'organic', 'garden care', 'soil nutrient'],
    keywords: ['organic fertilizer', 'plant food', 'garden fertilizer'],
    brand: 'EcoGrow', specifications: { Weight: '5 kg', NPK: '5-5-5', Ingredients: 'Seaweed + Worm Castings', Suitable: 'All Plants' },
  },
  {
    name: 'Folding Outdoor Chair Portable',
    description: 'Lightweight folding outdoor camping chair with padded armrests, cup holder, and carrying bag. Supports up to 120kg. Steel frame with breathable mesh back. Sets up in seconds. Ideal for garden, camping, and beach.',
    price: toINR(44.99), discountPrice: toINR(36.99), image: 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=400',
    stock: 30, sku: 'GRDN-CH-001', rating: 4.4, reviews: 198, isFeatured: false, isTrending: false,
    tags: ['outdoor chair', 'folding chair', 'camping chair', 'garden furniture'],
    keywords: ['folding outdoor chair', 'camping chair', 'portable garden chair'],
    brand: 'OutdoorEase', specifications: { WeightCapacity: '120 kg', Frame: 'Steel', Weight: '3.5 kg', Includes: 'Carrying Bag' },
  },
  {
    name: 'Grass Trimmer Electric Cordless',
    description: 'Cordless electric grass trimmer with 20V battery, 25cm cutting width, automatic line feed, and adjustable height. Lightweight at 2.3kg with ergonomic handle. Perfect for small to medium lawns.',
    price: toINR(89.99), discountPrice: toINR(72.99), image: 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=400',
    stock: 15, sku: 'GRDN-GT-001', rating: 4.2, reviews: 56, isFeatured: false, isTrending: false,
    tags: ['grass trimmer', 'lawn mower', 'garden tool', 'electric', 'cordless'],
    keywords: ['electric grass trimmer', 'cordless lawn trimmer', 'garden edger'],
    brand: 'LawnCare', specifications: { Battery: '20V Lithium', CuttingWidth: '25 cm', Runtime: '40 min', Weight: '2.3 kg' },
  },

  // ============ OFFICE & STATIONERY (7 products) ============
  {
    name: 'Standing Desk Adjustable Height',
    description: 'Electric height-adjustable standing desk with memory presets, 3 programmable positions, and anti-collision technology. Spacious 120x60cm desktop with cable management. Smooth and quiet motor for seamless transitions.',
    price: toINR(399.99), discountPrice: toINR(329.99), image: 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=400',
    stock: 10, sku: 'OFFC-DK-001', rating: 4.5, reviews: 67, isFeatured: true, isTrending: true, trendingRank: 43,
    tags: ['standing desk', 'adjustable desk', 'office furniture', 'ergonomic', 'work from home'],
    keywords: ['standing desk', 'height adjustable desk', 'electric desk'],
    brand: 'ErgoWork', specifications: { Size: '120x60cm', HeightRange: '72-120cm', Motor: 'Electric', Memory: '3 Presets' },
  },
  {
    name: 'Ergonomic Office Chair Mesh High Back',
    description: 'High-back mesh ergonomic office chair with lumbar support, adjustable headrest, 3D armrests, tilt lock, and smooth-rolling casters. Breathable mesh keeps you cool. Supports up to 150kg for 8+ hour comfort.',
    price: toINR(249.99), discountPrice: toINR(199.99), image: 'https://images.unsplash.com/photo-1580480055273-228ff5388ef8?w=400',
    stock: 15, sku: 'OFFC-CH-001', rating: 4.6, reviews: 89, isFeatured: true, isTrending: true, trendingRank: 44,
    tags: ['office chair', 'ergonomic chair', 'mesh chair', 'computer chair', 'furniture'],
    keywords: ['ergonomic office chair', 'mesh computer chair', 'high back chair'],
    brand: 'ComfortPlus', specifications: { Material: 'Mesh Back + Foam Seat', Lumbar: 'Adjustable', Armrest: '3D', Capacity: '150 kg' },
  },
  {
    name: 'Stationery Kit Complete Office Set',
    description: 'Complete 50-piece stationary kit including pens, pencils, markers, eraser, sharpener, scale, stapler, scissors, tape, paper clips, sticky notes, and more. Premium quality in a stylish organizer case.',
    price: toINR(29.99), discountPrice: toINR(24.99), image: 'https://images.unsplash.com/photo-1497215842964-222b4bef3739?w=400',
    stock: 80, sku: 'OFFC-SK-001', rating: 4.5, reviews: 234, isFeatured: true, isTrending: true, trendingRank: 45,
    tags: ['stationery set', 'office supplies', 'desk organizer', 'writing instruments'],
    keywords: ['office stationery kit', 'desk supplies set', 'complete stationary'],
    brand: 'WriteWell', specifications: { Pieces: '50', Includes: 'Pens+Pencils+Markers+Tools', Case: 'Organizer Included', Quality: 'Premium' },
  },
  {
    name: 'Wireless Keyboard and Mouse Combo',
    description: 'Ultra-slim wireless keyboard and mouse combo with 2.4GHz connection, quiet keys, adjustable DPI up to 1600, and energy-efficient design. Full-size keyboard with numeric pad. 12-month battery life.',
    price: toINR(34.99), discountPrice: toINR(27.99), image: 'https://images.unsplash.com/photo-1600269452121-4f2416e55c28?w=400',
    stock: 45, sku: 'OFFC-KM-001', rating: 4.4, reviews: 312, isFeatured: false, isTrending: true, trendingRank: 46,
    tags: ['keyboard mouse combo', 'wireless', 'office accessories', 'computer peripherals'],
    keywords: ['wireless keyboard mouse', 'office combo', 'computer accessories'],
    brand: 'TechType', specifications: { Connection: '2.4GHz', Range: '10m', Battery: '12 months', DPI: '800-1600' },
  },
  {
    name: 'Bookcase 5-Tier Storage Shelf',
    description: 'Sturdy 5-tier bookcase with open shelving for books, decor, and office supplies. 180cm tall with adjustable shelves. Made from engineered wood with scratch-resistant finish. Modern design fits any room.',
    price: toINR(129.99), discountPrice: toINR(99.99), image: 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=400',
    stock: 12, sku: 'OFFC-BC-001', rating: 4.3, reviews: 56, isFeatured: false, isTrending: false,
    tags: ['bookshelf', 'storage shelf', 'office furniture', 'home storage'],
    keywords: ['bookcase', '5-tier shelf', 'office storage'],
    brand: 'SpaceSavor', specifications: { Tiers: '5', Height: '180 cm', Material: 'Engineered Wood', Shelves: 'Adjustable' },
  },
  {
    name: 'Desk Lamp LED Eye Care Touch',
    description: 'LED desk lamp with touch control, 5 brightness levels, 3 color temperatures (warm, natural, cool), USB charging port, and flexible gooseneck. Flicker-free and anti-glare for comfortable reading and working.',
    price: toINR(39.99), discountPrice: toINR(32.99), image: 'https://images.unsplash.com/photo-1507473885765-e6ed057ab6fe?w=400',
    stock: 50, sku: 'OFFC-DL-001', rating: 4.5, reviews: 198, isFeatured: false, isTrending: false,
    tags: ['desk lamp', 'LED lamp', 'eye care', 'touch lamp', 'office lighting'],
    keywords: ['LED desk lamp', 'eye care lamp', 'touch control lamp'],
    brand: 'GlowWork', specifications: { Brightness: '5 Levels', ColorTemp: '3 Modes', USB: 'Charging Port', Power: '12W LED' },
  },
  {
    name: 'Monitor Stand Riser Adjustable',
    description: 'Adjustable monitor stand riser with height settings, sturdy aluminum construction, and spacious under-desk storage. Fits monitors up to 32 inches. Improves ergonomics by raising screen to eye level.',
    price: toINR(44.99), discountPrice: toINR(36.99), image: 'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=400',
    stock: 30, sku: 'OFFC-MS-001', rating: 4.4, reviews: 145, isFeatured: false, isTrending: false,
    tags: ['monitor stand', 'desk riser', 'ergonomic accessory', 'computer stand'],
    keywords: ['monitor riser', 'desk stand', 'computer monitor stand'],
    brand: 'ErgoBase', specifications: { Fits: 'Up to 32"', Material: 'Aluminum + ABS', Height: 'Adjustable 8-15cm', Weight: '10 kg max' },
  },

  // ============ MUSICAL INSTRUMENTS (7 products) ============
  {
    name: 'Acoustic Guitar Starter Kit',
    description: 'Complete acoustic guitar starter kit with 38" cutaway guitar, padded gig bag, tuner, extra strings, picks, strap, and beginner lesson booklet. Lindenwood body with spruce top for rich, resonant sound.',
    price: toINR(89.99), discountPrice: toINR(69.99), image: 'https://images.unsplash.com/photo-1510915361894-db8b60106cb1?w=400',
    stock: 20, sku: 'MUSC-GT-001', rating: 4.3, reviews: 78, isFeatured: true, isTrending: true, trendingRank: 47,
    tags: ['guitar', 'acoustic', 'musical instrument', 'starter kit', 'strings'],
    keywords: ['acoustic guitar', 'beginner guitar kit', 'starter guitar'],
    brand: 'MelodyStart', specifications: { Size: '38" Cutaway', Body: 'Lindenwood + Spruce', Strings: 'Steel', Accessories: 'Bag+Tuner+Picks+Book' },
  },
  {
    name: 'Electronic Keyboard Piano 61 Keys',
    description: '61-key electronic keyboard piano with velocity-sensitive keys, 255 tones, 255 rhythms, 60 demo songs, LCD display, and built-in speakers. Includes stand, bench, microphone, and power adapter. Perfect for beginners.',
    price: toINR(149.99), discountPrice: toINR(119.99), image: 'https://images.unsplash.com/photo-1552422535-c45813c61732?w=400',
    stock: 15, sku: 'MUSC-KB-001', rating: 4.4, reviews: 134, isFeatured: true, isTrending: true, trendingRank: 48,
    tags: ['keyboard', 'piano', 'electronic keyboard', 'music instrument', 'beginner'],
    keywords: ['electronic keyboard', '61 key piano', 'beginner keyboard'],
    brand: 'KeyTune', specifications: { Keys: '61 Velocity', Tones: '255', Rhythms: '255', Includes: 'Stand+Bench+Mic' },
  },
  {
    name: 'Professional Microphone Dynamic',
    description: 'Professional dynamic cardioid microphone with studio-grade sound, durable metal construction, built-in pop filter, and XLR cable. Ideal for vocals, podcasting, streaming, and live performances. Includes mic clip and case.',
    price: toINR(69.99), discountPrice: toINR(54.99), image: 'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=400',
    stock: 25, sku: 'MUSC-MC-001', rating: 4.5, reviews: 189, isFeatured: false, isTrending: true, trendingRank: 49,
    tags: ['microphone', 'dynamic mic', 'vocals', 'podcast', 'streaming'],
    keywords: ['professional microphone', 'dynamic microphone', 'vocal mic'],
    brand: 'SoundPro', specifications: { Type: 'Dynamic Cardioid', Frequency: '50Hz-15kHz', Connector: 'XLR', Includes: 'Clip + Case + Cable' },
  },
  {
    name: 'Drum Stool Padded Throne',
    description: 'Padded drum throne with heavy-duty tripod base, adjustable height from 45-60cm, and comfortable thick cushion seat. Non-slip rubber feet with memory foam seat for extended playing sessions. Supports up to 150kg.',
    price: toINR(69.99), discountPrice: toINR(54.99), image: 'https://images.unsplash.com/photo-1519892300165-cb5542fb47c7?w=400',
    stock: 12, sku: 'MUSC-DS-001', rating: 4.3, reviews: 45, isFeatured: false, isTrending: false,
    tags: ['drum stool', 'throne', 'drum accessory', 'music instrument stand'],
    keywords: ['drum throne', 'drum stool', 'padded drum seat'],
    brand: 'BeatBase', specifications: { Height: '45-60 cm', Seat: 'Memory Foam', Base: 'Tripod Heavy-Duty', Capacity: '150 kg' },
  },
  {
    name: 'Ukulele Soprano Starter Pack',
    description: 'Soprano ukulele starter pack with 21" mahogany wood ukulele, padded bag, digital tuner, extra strings, and beginner guide. Sweet bright tone with smooth playability. Perfect for kids and adults learning music.',
    price: toINR(39.99), discountPrice: toINR(32.99), image: 'https://images.unsplash.com/photo-1510915361894-db8b60106cb1?w=400',
    stock: 30, sku: 'MUSC-UK-001', rating: 4.5, reviews: 167, isFeatured: false, isTrending: false,
    tags: ['ukulele', 'soprano ukulele', 'string instrument', 'music', 'beginner'],
    keywords: ['ukulele starter pack', 'soprano ukulele', 'beginner ukulele'],
    brand: 'MelodyStart', specifications: { Size: '21" Soprano', Body: 'Mahogany', Strings: 'Nylon', Includes: 'Bag+Tuner+Strings' },
  },
  {
    name: 'Digital Piano Weighted Keys 88',
    description: 'Full-size 88-key digital piano with weighted hammer action keys, graded keyboard, Bluetooth connectivity, 128-note polyphony, and dual headphone jacks. Includes stand, bench, and sustain pedal. Stage-quality sound.',
    price: toINR(499.99), discountPrice: toINR(399.99), image: 'https://images.unsplash.com/photo-1552422535-c45813c61732?w=400',
    stock: 8, sku: 'MUSC-DP-001', rating: 4.7, reviews: 56, isFeatured: true, isTrending: true, trendingRank: 50,
    tags: ['digital piano', 'weighted keys', '88 key', 'piano', 'musical instrument'],
    keywords: ['digital piano', '88 key weighted', 'full size piano'],
    brand: 'KeyTune', specifications: { Keys: '88 Weighted Hammer', Polyphony: '128-note', Connectivity: 'Bluetooth', Includes: 'Stand+Bench+Pedal' },
  },
  {
    name: 'Guitar Pedal Effects Board',
    description: 'Multi-effects guitar pedal with 50+ effects including reverb, delay, distortion, chorus, wah, and more. Built-in tuner, looper, drum machine, and expression pedal input. Compact and durable design for stage and studio.',
    price: toINR(129.99), discountPrice: toINR(104.99), image: 'https://images.unsplash.com/photo-1510915361894-db8b60106cb1?w=400',
    stock: 12, sku: 'MUSC-GP-001', rating: 4.3, reviews: 34, isFeatured: false, isTrending: false,
    tags: ['guitar pedal', 'effects board', 'multi-effects', 'guitar accessory', 'music gear'],
    keywords: ['guitar effects pedal', 'multi effects board', 'stompbox'],
    brand: 'SoundPro', specifications: { Effects: '50+', Includes: 'Tuner+Looper+Drum', Input: 'Expression Pedal', Power: 'DC 9V' },
  },
];

async function seed() {
  try {
    console.log('Connecting to MongoDB...');
    await mongoose.connect(MONGODB_URI);
    console.log('Connected to MongoDB');

    // Clear existing data
    await Category.deleteMany({});
    await Product.deleteMany({});

    // Check if admin exists, if not create one
    const existingAdmin = await User.findOne({ email: 'admin@nextcart.com' });
    if (!existingAdmin) {
      await User.create({
        firstName: 'Admin',
        lastName: 'User',
        email: 'admin@nextcart.com',
        password: 'admin123',
        role: 'admin',
        phone: '+91 98765 43210',
      });
      console.log('Admin user created: admin@nextcart.com / admin123');
    } else {
      console.log('Admin user already exists');
    }

    // Create demo user
    const existingUser = await User.findOne({ email: 'test@nextcart.com' });
    if (!existingUser) {
      await User.create({
        firstName: 'Test',
        lastName: 'User',
        email: 'test@nextcart.com',
        password: 'test123',
        role: 'user',
        phone: '+91 98765 43210',
        address: {
          street: '123, MG Road',
          locality: 'Indiranagar',
          city: 'Bangalore',
          state: 'Karnataka',
          zipCode: '560038',
        },
      });
      console.log('Demo user created: test@nextcart.com / test123');
    }

    // Create categories
    const createdCategories = await Category.insertMany(categories);
    console.log(`Created ${createdCategories.length} categories`);

    // Map category names to IDs
    const categoryMap = {};
    createdCategories.forEach((cat) => {
      categoryMap[cat.name] = cat._id;
    });

    // Define category for each product section using comments as markers
    // Products are organized into sections by category. We need to track which section we're in.
    let currentCategory = '';
    const productsWithCategories = products.map((product) => {
      // Determine category from the product's SKU prefix or name-based rules
      const skuPrefix = product.sku ? product.sku.split('-')[0] : '';
      if (skuPrefix === 'ELEC') currentCategory = 'Electronics';
      else if (skuPrefix === 'CLTH') currentCategory = 'Clothing';
      else if (skuPrefix === 'HOME') currentCategory = 'Home & Kitchen';
      else if (skuPrefix === 'BOOK') currentCategory = 'Books';
      else if (skuPrefix === 'SPRT') currentCategory = 'Sports & Outdoors';
      else if (skuPrefix === 'BEAUTY') currentCategory = 'Beauty & Health';
      else if (skuPrefix === 'TOYS') currentCategory = 'Toys & Games';
      else if (skuPrefix === 'BABY') currentCategory = 'Baby Products';
      else if (skuPrefix === 'AUTO') currentCategory = 'Automotive';
      else if (skuPrefix === 'PET') currentCategory = 'Pet Supplies';
      else if (skuPrefix === 'GRDN') currentCategory = 'Garden & Outdoors';
      else if (skuPrefix === 'OFFC') currentCategory = 'Office & Stationery';
      else if (skuPrefix === 'MUSC') currentCategory = 'Musical Instruments';
      return { ...product, category: categoryMap[currentCategory] };
    });

    // Create products
    const createdProducts = await Product.insertMany(productsWithCategories);
    console.log(`Created ${createdProducts.length} products`);

    // Count by category
    const countByCategory = {};
    createdProducts.forEach((p) => {
      const cat = createdCategories.find((c) => c._id.toString() === p.category.toString());
      const catName = cat ? cat.name : 'Unknown';
      countByCategory[catName] = (countByCategory[catName] || 0) + 1;
    });

    console.log('\n✅ Seed data created successfully!');
    console.log('   Categories:', createdCategories.length);
    console.log('   Products:', createdProducts.length);
    console.log('\n📦 Products by Category:');
    Object.entries(countByCategory).forEach(([cat, count]) => {
      console.log(`   ${cat}: ${count} products`);
    });
    console.log('\n📝 Login Credentials:');
    console.log('   Admin: admin@nextcart.com / admin123');
    console.log('   Demo:  test@nextcart.com / test123');
    console.log('\n💰 All prices are in INR (₹)');
  } catch (error) {
    console.error('❌ Seed error:', error.message);
    process.exit(1);
  } finally {
    await mongoose.connection.close();
    console.log('Disconnected from MongoDB');
    process.exit(0);
  }
}

seed();
